FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

WORKDIR /app/src

ENV ACCOUNT_KEY=$ACCOUNT_KEY
ENV ACCOUNT_NAME=$ACCOUNT_NAME
ENV BENCHMARK_QNA=$BENCHMARK_QNA
ENV BENCHMARK_TG=$BENCHMARK_TG
ENV VALIDATION=$VALIDATION
ENV CONTAINER_NAME=$CONTAINER_NAME
ENV HUGGINGFACE_TOKEN=$HUGGINGFACE_TOKEN

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
