apiVersion: v1
kind: Service
metadata:
  name: responsive-ai-plat-service
spec:
  selector:
    app: responsive-ai-plat
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer